[package]
name = "lipu-tenpo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = {package = "ratatui", version = "0.20.1"}
crossterm = "0.26.1"
tui-input = "0.7.0"
clap = "*"
chrono = "*"
